### ISSUE TITLE
Замечания по паттерну "Наблюдатель"

### ISSUE THREAD

**Issue by alexey-malov** [daria-grebneva/OOD#1]
- [ ] Humidify -> Humidity

**Comment by iandreyshev** [comment]
- [x] Вынести классы и структуры из файла WeatherData.h в отдельные файлы
- [x] Члены класса должны быть названы в одном стиле
``` cpp
	CStats temperatureData;
	CStats humidityData;
	CStats pressureData;

	CStats temperatureData1;
	CStats humidityData1;
	CStats pressureData1;

	CWeatherData& m_in;
	CWeatherData& m_out;
```

- [x] Использовать конструкцию else if для проверки на m_out, чтобы наблюдатель работал только с  двумя наблюдаемыми объектами.

``` cpp
	void Update(SWeatherInfo const& data, const IObservable<SWeatherInfo>& obs) override
	{
		if (&obs == &m_in) //сравнивать указания на один и тот же объект
		{
			// some code
		}
		else
		{
			// some code
		}
	}
```

**Comment by iandreyshev** [comment]
[ ] - Разное форматирование типов аргументов функции "const$" и "const T&" , лучше использовать какой-то один вариант
``` cpp
void Update(SWeatherInfo const& data, const IObservable<SWeatherInfo>& obs) override
```
